save_data: mydata/sample
src_vocab: mydata/example.vocab.src
tgt_vocab: mydata/example.vocab.tgt
src_vocab_size: 44000
tgt_vocab_size: 44000
src_words_min_frequency: 3
tgt_words_min_frequency: 2
#-n_sample: -1
overwrite: False
#dump_samples: True
# Corpus opts:
data:
    coupus:
        path_src: mydata/src-train.txt
        path_tgt: mydata/tgt-train.txt
        transforms: [filtertoolong]  #filtertoolong
        weigth: 1
    valid:
        path_src: mydata/src-val.txt
        path_tgt: mydata/tgt-val.txt
        transforms: []
#### Filter
src_seq_length: 100
tgt_seq_length: 100

# silently ignore empty lines in the data
skip_empty_level: silent


#onmt_build_vocab -config wmt14_en_de.yaml -n_sample -1


# General opts
save_model: run/train_model
keep_checkpoint: 25
save_checkpoint_steps: 1000
average_decay: 0.0005
seed: 1234
report_every: 100
train_steps: 25000 #25000
valid_steps: 1000 #1000
# train_from: run/real_1000_model_step_9000.pt

# Batching
queue_size: 10000
bucket_size: 32768
world_size: 1
gpu_ranks: [0]
batch_type: "sents"
batch_size: 64  # A4000=64
valid_batch_size: 8
batch_size_multiple: 2
max_generator_batches: 0
accum_count: [4]
accum_steps: [0]

# Optimization
model_dtype: "fp32"
optim: "adam"
learning_rate: 2
warmup_steps: 8000
decay_method: "noam"
adam_beta2: 0.998
max_grad_norm: 0
label_smoothing: 0.1
param_init: 0
param_init_glorot: true
normalization: "sents"

# Model
encoder_type: transformer
decoder_type: transformer
#decoder_type2: transformer
enc_layers: 6
dec_layers: 6
#dec2_layers: 6
heads: 8
hidden_size: 512
word_vec_size: 512
transformer_ff: 2048
dropout_steps: [0]
dropout: [0.1]
attention_dropout: [0.1]
share_decoder_embeddings: true
# share_embeddings: true
position_encoding: true